import type { NodeId } from '@/algorithms/romania'
import { pathCost, type AlgoMeta } from '@/algorithms/search'
import { setALTPreset, setCustomLandmarks, saveALTState, restoreALTState, type LandmarkPreset } from '@/algorithms/heuristic'
import { cached, lmEffectCache, modernBenchCache } from '@/lib/benchCache'

export const BENCH_ITERS = 400

export type CompareRow = {
  key: string
  label: string
  ms: number
  peakFrontier: number
  generated: number
  cost: number
  hops: number
  found: boolean
}

// Point the module-level ALT heuristic at a specific preset/custom set, run the
// search, then restore whatever ALT state was active before — keeps the two
// lanes (and the benchmark tables) independent despite the shared module state.
export function withAltConfig<T>(preset: LandmarkPreset, custom: NodeId[], fn: () => T): T {
  const saved = saveALTState()
  if (preset === 'custom') {
    if (custom.length > 0) setCustomLandmarks(custom)
    else setALTPreset('lm8')
  } else {
    setALTPreset(preset)
  }
  try {
    return fn()
  } finally {
    restoreALTState(saved)
  }
}

// Benchmark a single algorithm under an explicit preset — mean wall time over
// BENCH_ITERS runs, plus peak frontier as a space proxy.
export function benchmarkOne(meta: AlgoMeta, start: NodeId, goal: NodeId, cfg: LandmarkPreset, custom: NodeId[]): CompareRow {
  // Cached across mounts (the memo above dies on unmount): remounting modern
  // after the game reran 800 searches for numbers that never change.
  return cached(modernBenchCache, `${meta.label}|${start}|${goal}|${cfg}|${custom.join(',')}`, () =>
    withAltConfig(cfg, custom, () => {
    const res = meta.run(start, goal)
    const t0 = performance.now()
    for (let i = 0; i < BENCH_ITERS; i++) meta.run(start, goal)
    const ms = (performance.now() - t0) / BENCH_ITERS
    const peakFrontier = res.steps.reduce((max, s) => Math.max(max, s.frontier.length), 0)
    return {
      key: '', label: meta.label, ms, peakFrontier,
      generated: res.generated,
      cost: res.found ? pathCost(res.path) : NaN,
      hops: res.found ? res.path.length - 1 : 0,
      found: res.found,
    }
  }))
}

// Nodes generated by one algorithm under each of the three landmark presets.
// Returns null for algorithms that do not use landmarks at all.
export function landmarkEffect(meta: AlgoMeta, start: NodeId, goal: NodeId): { lm2: number; lm4: number; lm8: number } | null {
  if (!meta.usesLandmarks) return null
  // Shared cache with the game UI: same (algo,start,goal) → same numbers
  return cached(lmEffectCache, `${meta.label}|${start}|${goal}`, () => {
    const saved = saveALTState()
    try {
      const out = {} as { lm2: number; lm4: number; lm8: number }
      for (const preset of ['lm2', 'lm4', 'lm8'] as const) {
        setALTPreset(preset)
        out[preset] = meta.run(start, goal).generated
      }
      return out
    } finally {
      restoreALTState(saved)
    }
  })
}
